name: Pack NuGet packages
description: Run dotnet pack
inputs: {}

runs:
  using: "composite"
  steps:
    - name: Pack Projects to NuGet packages
      shell: sh
      run: dotnet pack --no-restore --no-build -c Release
