<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ArtifactsPath>$(MSBuildThisFileDirectory)artifacts</ArtifactsPath>
    <ResultsPath>$(ArtifactsPath)/results/</ResultsPath>
    <SarifResultsPath>$(ResultsPath)/sarif/</SarifResultsPath>
    <UnitTestsResultPaths>$(ResultsPath)/unit-tests/</UnitTestsResultPaths>
    <CodeCoverageResultPaths>$(ResultsPath)/coverage/</CodeCoverageResultPaths>
    <CycloneDxResultPaths>$(ResultsPath)/cyclonedx/</CycloneDxResultPaths>
    <NuGetThirdPartyResultPaths>$(ResultsPath)/3rdpartyinfo/</NuGetThirdPartyResultPaths>
  </PropertyGroup>
</Project>
