<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ElementSolutionBuildDependsOn/>
  </PropertyGroup>

  <Import Project="$(MsBuildThisFileDirectory)/build/local/SarifGen.targets" />

  <Import Project="$(MsBuildThisFileDirectory)/build/local/CargoEdit.targets" />

  <Target Name="ElementSolutionPreBuild" BeforeTargets="Build" DependsOnTargets="$(ElementSolutionPreBuildDependsOn)" />
  <Target Name="ElementSolutionBuild" AfterTargets="Build" DependsOnTargets="$(ElementSolutionBuildDependsOn)" />
</Project>
