<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageVersionOverrideEnabled>false</CentralPackageVersionOverrideEnabled>
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" PrivateAssets="All" />
    <GlobalPackageReference Include="Microsoft.CodeAnalysis.PublicApiAnalyzers" Version="5.6.0" PrivateAssets="All" />
    <GlobalPackageReference Include="MinVer" Version="7.0.0" PrivateAssets="All" />
    <GlobalPackageReference Include="Dotnet.ReproducibleBuilds" Version="2.0.5" />
    <GlobalPackageReference Include="Meziantou.Analyzer" Version="3.0.194" />
    <GlobalPackageReference Include="SonarAnalyzer.CSharp" Version="10.33.0.1635" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>
  <Import Project="$(MsBuildThisFileDirectory)/deps/Docker.Images.props" />
</Project>
