[toolchain]
channel = "1.96.0"
components = [
    "rust-analyzer",
    "rust-src",
    "rustfmt",
    "clippy"
]
targets = [
    "aarch64-unknown-linux-gnu",
    "x86_64-unknown-linux-gnu",
    "aarch64-apple-darwin",
    "x86_64-apple-darwin"
]
profile = "minimal"
