[tools]
; renovate: datasource=crate depName=Clippy-Sarif packageName=clippy-sarif
clippy-sarif=0.8.0
; renovate: datasource=crate depName=Cargo-CycloneDX packageName=cargo-cyclonedx
cargo-cyclonedx=0.5.9
; renovate: datasource=crate depName=Cargo-edit packageName=cargo-edit
cargo-edit=0.13.13
; renovate: datasource=crate depName=jscpd packageName=jscpd
jscpd=5.0.15
; renovate: datasource=crate depName=Zigbuild packageName=cargo-zigbuild
cargo-zigbuild=0.23.2
