[tools]
; renovate: datasource=crate depName=Clippy-Sarif
clippy-sarif=0.8.0
; renovate: datasource=crate depName=Cargo-CycloneDX
cargo-cyclonedx=0.5.9
; renovate: datasource=crate depName=Cargo-edit
cargo-edit=0.13.13
; renovate: datasource=crate depName=JScpd
jscpd=5.0.15
; renovate: datasource=crate depName=Zigbuild
cargo-zigbuild=0.23.2
