[tools]
; renovate: datasource=cargo depName=Clippy-Sarif
clippy-sarif=0.8.0
; renovate: datasource=cargo depName=Cargo-CycloneDX
cargo-cyclonedx=0.5.9
; renovate: datasource=cargo depName=Cargo-edit
cargo-edit=0.13.13