<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <_ParentFile>$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))</_ParentFile>
  </PropertyGroup>

  <Import Project="$(_ParentFile)" Condition="'$(_ParentFile)' != '' AND Exists('$(_ParentFile)')" />

  <ItemGroup>
    <PackageVersion Include="Coverlet.MTP" Version="10.0.1" />
    <PackageVersion Include="Microsoft.Testing.Platform.MSBuild" Version="2.4.0" />
    <PackageVersion Include="TUnit" Version="1.65.68" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CrashDump" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.CtrfReport" Version="1.0.0-alpha.26452.8" />
    <PackageVersion Include="Microsoft.Testing.Extensions.JUnitReport" Version="1.0.0-alpha.26452.8" />
    <PackageVersion Include="Microsoft.Testing.Extensions.TrxReport" Version="2.4.0" />
    <PackageVersion Include="Microsoft.Testing.Extensions.GitHubActionsReport" Version="1.0.0-alpha.26377.5" />
  </ItemGroup>
</Project>
