// SPDX-Identifier: MIT
//
// (C) 2023-2026 Carsten Igel.
// Published under MIT License

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using HedgeCraft.Elements.SourceGenerators.ConfigurationPath;
using HedgeCraft.Elements.SourceGenerators.ConfigurationPath.Tests.Data;
using Microsoft.Extensions.Configuration;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.Diagnostics;
using Microsoft.CodeAnalysis.Text;
using TUnit;
using TUnit.Assertions;

namespace HedgeCraft.Elements.SourceGenerators.ConfigurationPath.Tests;

// AI GENERATED START - model: Copilot
internal sealed class ConfigurationPathGeneratorTests
{
    private static readonly ImmutableArray<MetadataReference> PlatformReferences =
        ((string)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES")!)
        .Split(Path.PathSeparator)
        .Select(static path => (MetadataReference)MetadataReference.CreateFromFile(path))
        .ToImmutableArray();

    [Test]
    public async Task EmitsAttributeInConfiguredRootNamespaceAndGeneratesNestedContexts()
    {
        GeneratorRun run = RunGenerator(Input.NestedModels, "Demo.Settings.Attributes");
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.AttributeNamespace, StringComparison.Ordinal) &&
            text.Contains(Expectations.MarkerAttribute, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.RootContext, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.ChildContext, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.ListValueContext, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.ArrayValueContext, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.GenericBoxContext, StringComparison.Ordinal) &&
            text.Contains(Expectations.GenericBoxConstraint, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.All(static text =>
            text.Contains(Expectations.GeneratedCodeAttribute, StringComparison.Ordinal) &&
            text.Contains("// <auto-generated />", StringComparison.Ordinal))).IsTrue();
        string generatorVersion = typeof(ConfigurationPathGenerator).Assembly
            .GetCustomAttributes(typeof(System.Reflection.AssemblyInformationalVersionAttribute), false)
            .OfType<System.Reflection.AssemblyInformationalVersionAttribute>()
            .FirstOrDefault()?.InformationalVersion
            ?? typeof(ConfigurationPathGenerator).Assembly
                .GetCustomAttributes(typeof(System.Reflection.AssemblyFileVersionAttribute), false)
                .OfType<System.Reflection.AssemblyFileVersionAttribute>()
                .FirstOrDefault()?.Version
            ?? "1.0.0.0-unkown";
        await Assert.That(run.GeneratedSources.All(text =>
            text.Contains($"\"{generatorVersion}\")]",
                StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.DefinitionList, StringComparison.Ordinal) &&
            text.Contains(Expectations.ChildContextReference, StringComparison.Ordinal))).IsTrue();
        string rootContext = run.GeneratedSources.Single(static text =>
            text.Contains("class ConfigurationContextOfRoot", StringComparison.Ordinal));
        await Assert.That(rootContext.Contains(Expectations.ReadOnlyPropertyTerm, StringComparison.Ordinal)).IsTrue();
        await Assert.That(rootContext.Contains("ReadOnlyName", StringComparison.Ordinal)).IsTrue();
        await Assert.That(rootContext.Contains("private static readonly", StringComparison.Ordinal)).IsTrue();
        await Assert.That(run.GeneratedHintNames.All(static name => name.EndsWith(".g.cs", StringComparison.Ordinal)))
            .IsTrue();
        await Assert.That(run.GeneratedHintNames.Distinct(StringComparer.Ordinal).Count())
            .IsEqualTo(run.GeneratedHintNames.Length);
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains("ConfigurationContextOfKeyModel", StringComparison.Ordinal))).IsFalse();
        await Assert.That(run.CompilationErrors).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task EmitsFallbackAttributeNamespaceWhenRootNamespaceIsUnavailable()
    {
        GeneratorRun run = RunGenerator(Input.FallbackNamespace, null);
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(Expectations.DefaultAttributeNamespace, StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains("ConfigurationContextOfSettings", StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.CompilationErrors).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task ReusesAnExistingContextImplementationForNestedModels()
    {
        GeneratorRun run = RunGenerator(Input.ExistingContext, "Demo.Context.Attributes");
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains("ConfigurationContextOfRoot", StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains(
                Expectations.ContextBaseType,
                StringComparison.Ordinal))).IsFalse();
        await Assert.That(run.GeneratedSources.Any(static text =>
            text.Contains("DumpConfigurationObject(", StringComparison.Ordinal) &&
            text.Contains("global::Existing.Context.ExistingChildContext", StringComparison.Ordinal))).IsTrue();
        await Assert.That(run.CompilationErrors).IsEqualTo(string.Empty);
    }

    [Test]
    public async Task DumpsNestedObjectsAndCollectionsWithParentKeys()
    {
        GeneratorRun run = RunGenerator(Input.NestedModels, "Demo.Settings.Attributes");
        System.Reflection.Assembly assembly = System.Reflection.Assembly.Load(run.AssemblyImage);
        Type rootType = assembly.GetType("Demo.Settings.Root")!;
        Type contextType = assembly.GetType("Demo.Settings.ConfigurationContextOfRoot")!;
        object root = Activator.CreateInstance(rootType)!;
        object child = rootType.GetProperty("Child")!.GetValue(root)!;
        child.GetType().GetProperty("Name")!.SetValue(child, "root child");
        child.GetType().GetProperty("Parent")!.SetValue(child, root);

        object box = rootType.GetProperty("Box")!.GetValue(root)!;
        object boxChild = box.GetType().GetProperty("Value")!.GetValue(box)!;
        boxChild.GetType().GetProperty("Name")!.SetValue(boxChild, "box child");

        ((System.Collections.IList)rootType.GetProperty("Children")!.GetValue(root)!).Add(child);

        object dictionaryChild = Activator.CreateInstance(assembly.GetType("Demo.Settings.Child")!)!;
        dictionaryChild.GetType().GetProperty("Name")!.SetValue(dictionaryChild, "dictionary child");
        object key = Activator.CreateInstance(assembly.GetType("Demo.Settings.KeyModel")!)!;
        ((System.Collections.IDictionary)rootType.GetProperty("Values")!.GetValue(root)!).Add(key, dictionaryChild);

        object context = Activator.CreateInstance(contextType, nonPublic: true)!;
        object?[] arguments = [root, true, new[] { "Parent" }];
        IReadOnlyDictionary<string, object?> values =
            (IReadOnlyDictionary<string, object?>)contextType.GetMethod("DumpConfigurationObject")!
                .Invoke(context, arguments)!;

        object?[] allPropertiesArguments = [root, false, Array.Empty<string>()];
        IReadOnlyDictionary<string, object?> allProperties =
            (IReadOnlyDictionary<string, object?>)contextType.GetMethod("DumpConfigurationObject")!
                .Invoke(context, allPropertiesArguments)!;
        await AssertDefaultDump(values, allProperties).ConfigureAwait(false);
        await AssertPathMetadata(contextType, context).ConfigureAwait(false);
    }

    [Test]
    public async Task GeneratedWritablePathsMatchConfigurationBinderBehavior()
    {
        GeneratorRun run = RunGenerator(Input.BindingScenario, "BindingScenario.Settings.Attributes");
        System.Reflection.Assembly assembly = System.Reflection.Assembly.Load(run.AssemblyImage);
        Type rootType = assembly.GetType("BindingScenario.Settings.Root")!;
        Type contextType = assembly.GetType("BindingScenario.Settings.ConfigurationContextOfRoot")!;
        object root = Activator.CreateInstance(rootType)!;

        Dictionary<string, string?> values = new(StringComparer.Ordinal)
        {
            ["renamed:Name"] = "bound child",
            ["ReadOnlyName"] = "ignored string",
            ["ReadOnlyScore"] = "42",
            ["NullableName"] = "bound nullable",
            ["NullableScore"] = "7",
        };
        IConfigurationRoot configuration = new ConfigurationBuilder()
            .AddInMemoryCollection(values)
            .Build();
        ConfigurationBinder.Bind(configuration, root);

        IReadOnlySet<string[]> writablePaths =
            (IReadOnlySet<string[]>)contextType.GetMethod("GetWritableConfigurationPaths")!
                .Invoke(Activator.CreateInstance(contextType, nonPublic: true), null)!;
        HashSet<string> generatedPaths = writablePaths
            .Select(static path => string.Join(":", path))
            .ToHashSet(StringComparer.Ordinal);
        object child = rootType.GetProperty("Child")!.GetValue(root)!;
        Dictionary<string, bool> binderResults = new(StringComparer.Ordinal)
        {
            ["renamed:Name"] = Equals(child.GetType().GetProperty("Name")!.GetValue(child), "bound child"),
            ["ReadOnlyName"] = !Equals(rootType.GetProperty("ReadOnlyName")!.GetValue(root), "read-only"),
            ["ReadOnlyScore"] = !Equals(rootType.GetProperty("ReadOnlyScore")!.GetValue(root), 9),
            ["NullableName"] = Equals(rootType.GetProperty("NullableName")!.GetValue(root), "bound nullable"),
            ["NullableScore"] = Equals(rootType.GetProperty("NullableScore")!.GetValue(root), 7),
        };

        foreach ((string path, bool binderAccepted) in binderResults)
        {
            if (generatedPaths.Contains(path) != binderAccepted)
            {
                throw new InvalidOperationException(
                    $"Generated writable paths differ from ConfigurationBinder for '{path}'.");
            }
        }
    }

    private static async Task AssertDefaultDump(
        IReadOnlyDictionary<string, object?> values,
        IReadOnlyDictionary<string, object?> allProperties)
    {
        await Assert.That(values["Parent:renamed:Name"]).IsEqualTo("root child");
        await Assert.That(values["Parent:Children:0:Name"]).IsEqualTo("root child");
        await Assert.That(values["Parent:Box:Value:Name"]).IsEqualTo("box child");
        await Assert.That(values["Parent:Scores:0"]).IsEqualTo(3);
        await Assert.That(values["Parent:Scores:1"]).IsEqualTo(4);
        await Assert.That(((byte[])values["Parent:Blob"]!).SequenceEqual(new byte[] { 5, 6 })).IsTrue();
        await Assert.That(values.ContainsKey("Parent:Blob:0")).IsFalse();
        string dictionaryValue = values.First(entry =>
            entry.Key.StartsWith("Parent:Values:", StringComparison.Ordinal) &&
            entry.Key.EndsWith(":Name", StringComparison.Ordinal)).Value!.ToString()!;
        await Assert.That(dictionaryValue).IsEqualTo("dictionary child");
        await Assert.That(values.ContainsKey("Parent:ReadOnlyName")).IsFalse();
        await Assert.That(values.ContainsKey("Parent:ReadOnlyScore")).IsFalse();
        await Assert.That(values["Parent:NullableName"]).IsNull();
        await Assert.That(values["Parent:NullableScore"]).IsNull();
        await Assert.That(allProperties["ReadOnlyName"]).IsEqualTo("read-only");
        await Assert.That(allProperties["ReadOnlyScore"]).IsEqualTo(9);
    }

    private static async Task AssertPathMetadata(Type contextType, object context)
    {
        IReadOnlySet<string[]> readable =
            (IReadOnlySet<string[]>)contextType.GetMethod("GetReadableConfigurationPaths")!.Invoke(context, null)!;
        IReadOnlySet<string[]> writable =
            (IReadOnlySet<string[]>)contextType.GetMethod("GetWritableConfigurationPaths")!.Invoke(context, null)!;
        await Assert.That(readable.Contains(["renamed", "Name"])).IsTrue();
        await Assert.That(readable.Contains(["Box", "Value", "Name"])).IsTrue();
        await Assert.That(writable.Contains(["renamed", "Name"])).IsTrue();
        await Assert.That(writable.Contains(["renamed"])).IsFalse();
    }

    private static GeneratorRun RunGenerator(string source, string? rootNamespace)
    {
        CSharpParseOptions parseOptions = new(LanguageVersion.CSharp14);
        CSharpCompilation compilation = CSharpCompilation.Create(
            string.Concat("GeneratorTests_", Guid.NewGuid().ToString("N")),
            [CSharpSyntaxTree.ParseText(SourceText.From(source), parseOptions)],
            PlatformReferences,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

        GeneratorDriver driver = CSharpGeneratorDriver.Create(
            [new ConfigurationPathGenerator().AsSourceGenerator()],
            parseOptions: parseOptions,
            optionsProvider: new TestAnalyzerConfigOptionsProvider(rootNamespace));
        driver = driver.RunGeneratorsAndUpdateCompilation(compilation, out Compilation updatedCompilation, out _);
        ImmutableArray<string> generatedSources = driver.GetRunResult()
            .Results
            .SelectMany(static result => result.GeneratedSources)
            .Select(static generated => generated.SourceText.ToString())
            .ToImmutableArray();
        ImmutableArray<string> generatedHintNames = driver.GetRunResult()
            .Results
            .SelectMany(static result => result.GeneratedSources)
            .Select(static generated => generated.HintName)
            .ToImmutableArray();

        string compilationErrors = string.Join(
            Environment.NewLine,
            updatedCompilation.GetDiagnostics()
                .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                .Select(static diagnostic => string.Concat(
                    diagnostic.Id,
                    ": ",
                    diagnostic.GetMessage(CultureInfo.InvariantCulture))));
        using MemoryStream output = new();
        Microsoft.CodeAnalysis.Emit.EmitResult emitResult = updatedCompilation.Emit(output);
        if (!emitResult.Success)
        {
            compilationErrors = string.Join(
                Environment.NewLine,
                emitResult.Diagnostics
                    .Where(static diagnostic => diagnostic.Severity == DiagnosticSeverity.Error)
                    .Select(static diagnostic => string.Concat(
                        diagnostic.Id,
                        ": ",
                        diagnostic.GetMessage(CultureInfo.InvariantCulture))));
        }

        return new GeneratorRun(
            generatedSources,
            generatedHintNames,
            compilationErrors,
            emitResult.Success ? output.ToArray() : []);
    }

    private sealed record GeneratorRun(
        ImmutableArray<string> GeneratedSources,
        ImmutableArray<string> GeneratedHintNames,
        string CompilationErrors,
        byte[] AssemblyImage);

    private sealed class TestAnalyzerConfigOptionsProvider : AnalyzerConfigOptionsProvider
    {
        public TestAnalyzerConfigOptionsProvider(string? rootNamespace)
        {
            Dictionary<string, string> options = new(StringComparer.OrdinalIgnoreCase);
            if (rootNamespace is not null)
            {
                options["build_property.RootNamespace"] = rootNamespace;
            }

            this.GlobalOptions = new TestAnalyzerConfigOptions(options);
        }

        public override AnalyzerConfigOptions GlobalOptions { get; }

        public override AnalyzerConfigOptions GetOptions(SyntaxTree tree)
        {
            return TestAnalyzerConfigOptions.Empty;
        }

        public override AnalyzerConfigOptions GetOptions(AdditionalText textFile)
        {
            return TestAnalyzerConfigOptions.Empty;
        }
    }

    private sealed class TestAnalyzerConfigOptions(IDictionary<string, string> options) : AnalyzerConfigOptions
    {
        public static TestAnalyzerConfigOptions Empty { get; } =
            new(new Dictionary<string, string>(StringComparer.Ordinal));

        public override bool TryGetValue(string key, out string value)
        {
            return options.TryGetValue(key, out value!);
        }
    }
}
// AI GENERATED END
