<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <ProjectReference Include="../../gen/Elements.SourceGenerators.ConfigurationPath/Elements.SourceGenerators.ConfigurationPath.csproj" />
  </ItemGroup>
</Project>
