name: Create cachable docker image
description: Pre-build the images required for building rust based parts
inputs: {}

runs:
  using: "composite"
  steps:
      - name: Setup docker image builder
        uses: docker/setup-buildx-action@v4
      - name: Build and load
        uses: docker/build-push-action@v7
        with:
          file: build/local/docker/cargo/Dockerfile
          tags: carstencodes/elements/cargo-build-cross:ci
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          load: true
      - name: Verify image exists
        shell: sh
        run: docker image ls carstencodes/elements/cargo-build-cross:ci
