name: Download artifacts
description: Download artifacts from a previous job
inputs:
  name:
    description: The name of the artifact to download
    required: true
    type: string
  path:
    description: The path to download the artifact to
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Download artifact
      uses: actions/download-artifact@v8
      id: download
      with:
        name: ${{ inputs.name }}
        path: ${{ runner.temp }}/artifacts/${{ inputs.path }}
        digest-mismatch: error
    - name: Create artifact folder
      shell: sh
      run: mkdir -p ${{ inputs.path }}
    - name: Decompress artifact
      shell: sh
      run: |
        tar -zxf ${{ steps.download.output.download-path }}/*.tar.gz -C ${{ inputs.path }}
