[package]
name = "posixioelements"
version = { workspace = true }
authors = { workspace = true }
description = { workspace = true }
documentation = { workspace = true }
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
rustix = { workspace = true }

[build-dependencies]
csbindgen = { workspace = true }
