<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <RustSourceFile Include="src/**/*.rs" />
    <RustBuildFile Include="build.rs" Link="build/build.rs" />
    <RustBuildFile Include="Cargo.toml" Link="build/Cargo.toml" />
    <RustBuildFile Include="$(SolutionDir)/Cargo.lock" Link="build/Cargo.lock" Condition="Exists('$(SolutionDir)/Cargo.lock')" />
  </ItemGroup>

  <PropertyGroup>
    <_ParentFile>$([MSBuild]::GetPathOfFileAbove('$(MSBuildThisFile)', '$(MSBuildThisFileDirectory)../'))</_ParentFile>
  </PropertyGroup>

  <Import Project="$(_ParentFile)" Condition="'$(_ParentFile)' != '' AND Exists('$(_ParentFile)')" />

  <Import Project="$(MsBuildThisFileDirectory)DockerCargo.targets" Condition="'$(CargoBuildEngine)' == 'Docker'" />
  <Import Project="$(MsBuildThisFileDirectory)NativeCargo.targets" Condition="'$(CargoBuildEngine)' != 'Docker'" />

</Project>
