<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <TargetsTriggeredByCompilation>
      $(TargetsTriggeredByCompilation);
      RunNativeCargoBuild;
      CargoCreateSarifFileWithClippy;
    </TargetsTriggeredByCompilation>
    <CoreCleanDependsOn>
      $(CoreCleanDependsOn);
      RunNativeCargoClean
    </CoreCleanDependsOn>
    <GenerateCycloneDxDocumentDependsOn>
        CycloneDxSetToolConfigurationRustProj;
        $(GenerateCycloneDxDocumentDependsOn)
    </GenerateCycloneDxDocumentDependsOn>
    <PackCycloneDxFileDependsOn>
      MoveCycloneDxFileToResultsFolder;
      $(PackCycloneDxFileDependsOn)
    </PackCycloneDxFileDependsOn>
  </PropertyGroup>

  <PropertyGroup>
    <CargoConfiguration />
    <CargoConfiguration Condition="'$(Configuration)' == 'Release'">--release</CargoConfiguration>
  </PropertyGroup>

  <PropertyGroup>
    <ConfigurationOutputFolder>$(Configuration.ToLowerInvariant())</ConfigurationOutputFolder>
  </PropertyGroup>

  <ItemGroup>
    <DependencyDefinitionFiles Remove="$(DependencyDefinitionFiles)" />
    <DependencyDefinitionFiles Include="$(MsBuildProjectFile)" />
    <DependencyDefinitionFiles Include="$(MSBuildProjectDirectory)/Cargo.toml" />
    <DependencyDefinitionFiles Include="$(MSBuildProjectDirectory)/Cargo.lock" Condition="Exists('$(MSBuildProjectDirectory)/Cargo.lock')" />
    <DependencyDefinitionFiles Include="$(SolutionDir)/Cargo.lock" Condition="Exists('$(SolutionDir)/Cargo.lock')" />
    <DependencyDefinitionFiles Include="$(SolutionDir)/deps/cargo-tools.ini" Condition="Exists('$(SolutionDir)/deps/cargo-tools.ini')" />
  </ItemGroup>

  <ItemGroup>
    <CargoEnvironment Include="SDKROOT" Value="/dev/null" />
  </ItemGroup>

  <Target Name="CargoGetTargetDirectories">
    <PropertyGroup>
        <CargoTargetDirectory Condition="'$(CargoTargetDirectory)' == ''">$(IntermediateOutputPath)target</CargoTargetDirectory>
    </PropertyGroup>

    <ItemGroup>
        <CargoBuildIdentifiers Include="@(BuildIdentifiers)">
            <TargetFilePath>$(CargoTargetDirectory)/%(BuildIdentifiers.CargoRustTarget)/$(CargoBuildTarget)/$(ConfigurationOutputFolder)/%(BuildIdentifiers.DyLibFilePrefix)$(RustCrateLibName)%(BuildIdentifiers.DyLibExtension)</TargetFilePath>
            <TargetFileName>%(BuildIdentifiers.DyLibFilePrefix)$(RustCrateLibName)</TargetFileName>
            <TargetExtension>%(BuildIdentifiers.DyLibExtension)</TargetExtension>
            <DotnetRuntimeIdentifier>%(BuildIdentifiers.DotnetRuntimeIdentifier)</DotnetRuntimeIdentifier>
        </CargoBuildIdentifiers>
    </ItemGroup>

    <ItemGroup>
        <CargoIntermediateOutputFiles Include="@(CargoBuildIdentifiers->'%(TargetFilePath)')">
            <CargoRustTarget>%(CargoBuildIdentifiers.CargoRustTarget)</CargoRustTarget>
            <TargetFileName>%(CargoBuildIdentifiers.TargetFileName)</TargetFileName>
            <TargetExtension>%(CargoBuildIdentifiers.TargetExtension)</TargetExtension>
            <DotnetRuntimeIdentifier>%(CargoBuildIdentifiers.DotnetRuntimeIdentifier)</DotnetRuntimeIdentifier>
        </CargoIntermediateOutputFiles>
    </ItemGroup>

    <ItemGroup>
        <CargoOutputFiles Include="@(CargoIntermediateOutputFiles->'$(OutDir)%(CargoRustTarget)/%(TargetFileName)%(TargetExtension)')">
            <SourceFile>%(CargoIntermediateOutputFiles.Identity)</SourceFile>
            <TargetDir>$(OutDir)/%(CargoRustTarget)</TargetDir>
            <DotnetRuntimeIdentifier>%(CargoIntermediateOutputFiles.DotnetRuntimeIdentifier)</DotnetRuntimeIdentifier>
        </CargoOutputFiles>
    </ItemGroup>
  </Target>

  <Target Name="CargoCreateSarifFileWithClippy" Condition="'$(ErrorLog)' != ''">
    <PropertyGroup>
      <ClippyChecks />
      <ClippyChecks>$(ClippyChecks) -D clippy::correctness</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::correctness</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::suspicious</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::style</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::complexity</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::perf</ClippyChecks>
      <ClippyChecks>$(ClippyChecks) -W clippy::pedantic</ClippyChecks>
    </PropertyGroup>

    <Exec Command="cargo clippy --all-targets --all-features --message-format=json -- $(ClippyChecks)"
          ContinueOnError="warnAndContinue"
          ConsoleToMSBuild="true"
          IgnoreStandardErrorWarningFormat="true"
          IgnoreExitCode="false">
      <Output TaskParameter="ExitCode" PropertyName="CargoClippyExitCode" />
      <Output TaskParameter="ConsoleOutput" ItemName="CargoClippyConsoleOutput" />
    </Exec>

    <WriteLinesToFile File="$(IntermediateOutputPath)/cargo.clippy.output.json"
                      Lines="@(CargoClippyConsoleOutput)"
                      Overwrite="true"
                      WriteOnlyWhenDifferent="true" />

    <PropertyGroup>
      <LastSemicolonIndexInErrorLog>$([System.String]::Copy('$(ErrorLog)').LastIndexOf(';'))</LastSemicolonIndexInErrorLog>
      <CargoErrorLog>$(ErrorLog)</CargoErrorLog>
      <CargoErrorLog Condition="$(LastSemicolonIndexInErrorLog) &gt; 0">$([System.String]::Copy('$(ErrorLog)').Substring(0, $(LastSemicolonIndexInErrorLog)))</CargoErrorLog>
    </PropertyGroup>

    <Exec Command="clippy-sarif -i &quot;$(IntermediateOutputPath)/cargo.clippy.output.json&quot; -o &quot;$(CargoErrorLog)&quot;"
          ContinueOnError="warnAndContinue"
          ConsoleToMSBuild="true"
          IgnoreStandardErrorWarningFormat="true"
          IgnoreExitCode="false">
      <Output TaskParameter="ExitCode" PropertyName="CargoClippyExitCode" />
      <Output TaskParameter="ConsoleOutput" ItemName="CargoClippyConsoleOutput" />
    </Exec>

    <ItemGroup>
      <FileWrites Include="$(CargoErrorLog)" />
    </ItemGroup>
  </Target>

  <Target Name="RunNativeCargoBuild" DependsOnTargets="CargoGetTargetDirectories;CargoCreateSarifFileWithClippy;CreateSbomCycloneDxUsingCargo" Inputs="@(RustSourceFile);@(RustBuildFile)" Outputs="@(CargoOutputFiles)" Returns="@(CreatedFilesByCargoBuild)">
    <Exec
        Command="cargo %(BuildIdentifiers.CargoBuildCommand) $(CargoConfiguration) --target-dir &quot;$(CargoTargetDirectory)&quot; --target &quot;%(BuildIdentifiers.CargoRustTarget)&quot;"
        EnvironmentVariables="@(CargoEnvironment->'%(Identity)=%(Value)')"
        />

    <ItemGroup>
      <CreatedFilesByCargoBuild Include="@(CargoOutputFiles)">
        <TargetFrameworkIdentifier>$(TargetFramework)</TargetFrameworkIdentifier>
        <TargetPlatformMoniker>%(CargoOutputFiles.DotnetRuntimeIdentifier)</TargetPlatformMoniker>
        <TargetPlatformIdentifier>%(CargoOutputFiles.DotnetRuntimeIdentifier)</TargetPlatformIdentifier>
        <CopyUpToDateMarker />
        <TargetFrameworkVersion />
        <ReferenceAssembly />
        <RuntimeIdentifier>%(CargoOutputFiles.DotnetRuntimeIdentifier)</RuntimeIdentifier>
        <Configuration>$(Configuration)</Configuration>
      </CreatedFilesByCargoBuild>
    </ItemGroup>

    <MakeDir Directories="%(CargoOutputFiles.TargetDir)" />

    <Copy SourceFiles="%(CargoOutputFiles.SourceFile)" DestinationFolder="%(CargoOutputFiles.TargetDir)" />

    <ItemGroup>
      <FileWrites Include="@(CargoOutputFiles)" />
    </ItemGroup>

    <ItemGroup>
      <CreatedFilesByCargoBuild Include="@(NativeAssetReference->WithMetadataValue('AssetType', 'Content'))">
        <AssetType>Content</AssetType>
      </CreatedFilesByCargoBuild>
      <TargetPathWithTargetPlatformMoniker Include="@(CreatedFilesByCargoBuild)" />
    </ItemGroup>
  </Target>

  <Target Name="RunNativeCargoClean" DependsOnTargets="CargoGetTargetDirectories">
    <Exec
        Command="cargo clean --target-dir &quot;$(CargoTargetDirectory)&quot;"
        EnvironmentVariables="@(CargoEnvironment->'%(Identity)=%(Value)')"
        />
  </Target>

  <Target Name="RunNativeCargoFetch">
    <Exec
        Command="cargo fetch --target &quot;%(BuildIdentifiers.CargoRustTarget)&quot;"
        EnvironmentVariables="@(CargoEnvironment->'%(Identity)=%(Value)')"
        />
  </Target>

  <Target Name="CycloneDxSetToolConfigurationRustProj">
    <PropertyGroup Condition="'$(CycloneDxType)' == ''">
      <CycloneDxType>library</CycloneDxType>
    </PropertyGroup>

    <PropertyGroup>
        <CycloneDxToolLauncher>cargo</CycloneDxToolLauncher>
        <CycloneDxCommandName>cyclonedx</CycloneDxCommandName>
        <CycloneDxToolArguments />
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --manifest-path '$(MSBuildProjectDirectory)/Cargo.toml'</CycloneDxToolArguments>
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --format '$(CycloneDxOutputFormat)'</CycloneDxToolArguments>
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --all-features</CycloneDxToolArguments>
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --all</CycloneDxToolArguments>
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --spec-version '$(CycloneDxVersion)'</CycloneDxToolArguments>
        <CycloneDxToolArguments>$(CycloneDxToolArguments) --override-filename '$(MsBuildProjectName).cyclonedx'</CycloneDxToolArguments>
        <CycloneDxToolInvocation>$(CycloneDxToolLauncher) $(CycloneDxCommandName) $(CycloneDxToolArguments)</CycloneDxToolInvocation>
    </PropertyGroup>

    <PropertyGroup>
        <CycloneDxResultsExecDir>$(CycloneDxResultDirectory)</CycloneDxResultsExecDir>
      </PropertyGroup>
  </Target>

  <Target Name="MoveCycloneDxFileToResultsFolder" Inputs="$(MSBuildProjectDirectory)/$(CycloneDxResultFileName)" Outputs="$(CycloneDxResultFilePath)">
    <Move SourceFiles="$(MSBuildProjectDirectory)/$(CycloneDxResultFileName)" DestinationFolder="$(CycloneDxResultDirectory)"  Condition="Exists('$(MSBuildProjectDirectory)/$(CycloneDxResultFileName)')" />
  </Target>

  <Target Name="CreateSbomCycloneDxUsingCargo" DependsOnTargets="CreateSbomCycloneDx;MoveCycloneDxFileToResultsFolder" Returns="@(NativeAssetReference)" Condition="'$(GenerateCycloneDxSbom)' == 'true'">
    <ItemGroup Condition="Exists('$(CycloneDxResultFilePath)')">
      <NativeAssetReference Include="$(CycloneDxResultFilePath)">
        <AssetType>Content</AssetType>
      </NativeAssetReference>
    </ItemGroup>
  </Target>
</Project>
