// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Elements.IO.Posix.Internal
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "posixioelements";





        /// <summary>
        ///  External
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fs_owning_user_name", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern ushort fs_owning_user_name();


    }



}
