name: Create SBOM
description: Create a Software Bill of Materials (SBOM) for the project
inputs: {}

runs:
  using: "composite"
  steps:
    - name: Create CycloneDX files
      run: dotnet msbuild --configuration Release -t:CreateSbomCycloneDx
    - name: Create NuGetLicenseInformation files
      run: dotnet msbuild --configuration Release -t:CreateNuGetLicenseOutputFile
