name: Pre-Build Checks
description: Check the codebase for common issues before building and testing
inputs:
  nested_action_version:
    description: The version of the nested action to use
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v7
    - uses: .github/actions/toolchain@${{ inputs.nested_action_version }}
    - uses: pre-commit/action@v3.0.1
