<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Elements.IO.Posix.native-assets/Elements.IO.Posix.native-assets.msbuildproj">
      <IncludeAssets>native</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
      <SkipGetTargetFrameworkProperties>true</SkipGetTargetFrameworkProperties>
      <SetTargetFramework>TargetFramework=$(TargetFramework)</SetTargetFramework>
      <OutputItemType>NativeAssetReference</OutputItemType>
      <ReferenceOutputAssembly>false</ReferenceOutputAssembly>
    </ProjectReference>
  </ItemGroup>
</Project>
