name: Continuous Integration
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  NUGET_PACKAGES: ${{ github.workspace }}/deps/nuget/

jobs:

#####################################################################
#
# Initialize the pipeline runs
#
#####################################################################

  initialize:
    name: Pipeline initization
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: NOOP
        run: echo "NOOP"

#####################################################################
#
# Perform checks
#
#####################################################################

  checks:
    name: Basic Pre-Build Checks
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: true
          fetch-tags: true
          submodules: false
          fetch-depth: 0
      - uses: ./.github/actions/checks

#####################################################################
#
# Build the project and run code checks
#
#####################################################################

  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    needs:
      - initialize
      - checks
    strategy:
      matrix:
        configuration: [ 'Debug', 'Release' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: true
          fetch-tags: true
          submodules: false
          fetch-depth: 0
      - name: Restore
        uses: ./.github/actions/restore
        with:
          tool_restore: true
      - name: Build
        uses: ./.github/actions/build
        with:
          configuration: ${{ matrix.configuration }}
      - name: Publish SARIF files
        uses: github/codeql-action/upload-sarif@v4
        if: ${{ matrix.configuration == 'Release' }}
        with:
          sarif_file: artifacts/Elements.sarif
      - Name: Upload artifacts folder
        uses: actions/upload-artifact@v7
        if: ${{ matrix.configuration == 'Release' }}
        with:
          name: artifacts
          path: artifacts/
          if-no-files-found: error
          retention-days: 7
          include-hidden-files: true
          archive: true

#####################################################################
#
# Create the software bill of materials
#
#####################################################################

  sbom:
    name: Software Bill-Of-Materials
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: true
          fetch-tags: true
          submodules: false
          fetch-depth: 0
      - name: Restore
        uses: ./.github/actions/restore
        with:
          tool_restore: true
      - name: Create SBOM
        uses: ./.github/actions/sbom

#####################################################################
#
# Test the project and also create code coverage reports
#
#####################################################################

  test:
    name: Run Unit-Tests
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          clean: true
          fetch-tags: true
          submodules: false
          fetch-depth: 0
      - name: Restore
        uses: ./.github/actions/restore
        with:
          tool_restore: true
      - name: Get Build Results
        uses: actions/download-artifact@v8
        with:
          name: artifacts
          skip-decompress: false
          digest-mismatch: error
      - name: Run tests
        run: dotnet test --no-restore --no-build --configuration Release
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@v5.5.11
        if: ${{ !always() }}
        with:
          reports: artifacts/results/coverage/*.xml
          targetdir: artifacts/
          reporttypes: Cobertura;MarkdownSummaryGithub

#####################################################################
#
# Pack the projects to nuget
#
#####################################################################

  pack:
    name: Pack NuGet Package
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs:
      - test
      - build
      - sbom
    steps:
      - name: NOOP
        run: echo "NOOP"

#####################################################################
#
# Summarize the build
#
#####################################################################

  summarize:
    name: Build Summary
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
    needs:
      - build
      - test
      - pack
    steps:
      - name: NOOP
        run: echo "NOOP"
