name: pre-commit

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo install --locked cargo-clippy cargo-fmt
    - uses: pre-commit/action@v3.0.1
